# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.define "selector" do |tutorial|
  end
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Selector" + Time.now.strftime(" %Y-%m-%d")
    vb.gui = true
    vb.memory = 2048
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
  end
  config.vm.synced_folder '.', '/vagrant', disabled: true  
  config.vm.hostname = "selector"
  config.vm.provision "shell", path: "root-bootstrap.sh"
  config.vm.provision "shell", privileged: false, path: "user-bootstrap.sh"
end
